Add example of incremental, name based parsing
haskell-hvr/cassava pull request #209
Opened 2021-12-20 21:26 UTC by MaxGabriel

There is already an example for indexed-based decoding, but not for name-based.

This also adds a salaries.csv file, which is used by the new code, but incidentally closes https://github.com/haskell-hvr/cassava/issues/208

2021-12-20 21:30 UTC, MaxGabriel commented
Fwiw, I've never used the incremental CSV parsing stuff, so I'm mostly cargo-culting from the indexed based version and puzzling things out/playing type tetris. But, this compiles/runs, so that's a good sign

2021-12-21 14:06 UTC, andreasabel requested changes
Thanks for the PR!

2021-12-21 14:06 UTC, andreasabel commented on examples/IncrementalNameBasedDecode.hs
> +                else k `fmap` B.hGetSome csvFile 4096
Use `k <$> ...` instead of `k ``fmap`` ...`.

2021-12-21 14:06 UTC, andreasabel commented on examples/IncrementalNameBasedDecode.hs
> +        feed k = do
`feed` looks like an identical clone of `feedHeader`.  Please get rid of one of them.

2021-12-21 14:06 UTC, andreasabel commented on examples/IncrementalNameBasedDecode.hs
> +      let good = rights rs
What happens to the `lefts`?  Is `Left s` an error message?  
Usually, swallowing errors is not a good idea.  These errors should be raised.  (If these are errors.)

2021-12-21 14:06 UTC, andreasabel commented on examples/IncrementalNameBasedDecode.hs
> +      in sum $ map (\sinfo -> salary sinfo) good
Unnecessary lambda?  Does `sum $ map salary good` also work?

2021-12-21 15:25 UTC, closed without merging

2021-12-21 16:46 UTC, andreasabel commented
@MaxGabriel Why did you close the PR now?

2022-01-05 14:48 UTC, andreasabel commented
ping @MaxGabriel